//
// locationType.cs.cs
//
// This file was generated by XMLSPY 5 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSPY Documentation for further details.
// http://www.altova.com/xmlspy
//


using Altova.Types;

namespace modullist
{

	public class locationType : SchemaString
	{
		public locationType(string newValue) : base(newValue)
		{
			Validate();
		}

		public void Validate()
		{
		}
	}
}
